source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.1'

flutter_application_path = '../flutter_module_test'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
    

target 'iOS_test1' do
  install_all_flutter_pods(flutter_application_path)
end
